version: "3.5"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root

  nginx:
    platform: linux/x86_64
    build: docker/nginx
    ports:
      - "8080:80"
    environment:
      PHP_FPM_IP: app
      PHP_FPM_PORT: 9000
    volumes:
      - .:/app

  app:
    platform: linux/x86_64
    build:
      context: docker/php
      target: base
    environment:
      DATABASE_URL: "mysql://app:app@mysql:3306/app?serverVersion=8"
    volumes:
      - .:/app
    depends_on:
      - mysql
