# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    BookShop\:
        resource: '../src/'
        exclude:
            - '../src/Application/Query/BackOffice/Author/Author.php'
            - '../src/Application/Query/BackOffice/Book/Book.php'
            - '../src/Application/Query/Shop/Book/Author.php'
            - '../src/Application/Query/Shop/Book/Book.php'
            - '../src/Domain/'
            - '../src/Kernel.php'

    BookShop\Ports\ShopApi\Controller\:
        resource: '../src/Ports/ShopApi/Controller/'
        tags: ['controller.service_arguments']

    BookShop\Ports\BackOfficeApi\Controller\:
        resource: '../src/Ports/BackOfficeApi/Controller/'
        tags: [ 'controller.service_arguments' ]
