parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    BookShop\:
        resource: '../src/'
        exclude:
            - '../src/Application/Command/'
            - '../src/Application/Query/'
            - '../src/Domain/'
            - '../src/Kernel.php'

    BookShop\Ports\ShopApi\Controller\:
        resource: '../src/Ports/ShopApi/Controller/'
        tags: ['controller.service_arguments']

    BookShop\Ports\BackOfficeApi\Controller\:
        resource: '../src/Ports/BackOfficeApi/Controller/'
        tags: [ 'controller.service_arguments' ]

    BookShop\Application\Command\:
        resource: '../src/Application/Command/**/**Handler.php'
        tags: [ messenger.message_handler ]

    BookShop\Application\Query\:
        resource: '../src/Application/Query'
        exclude:
            - '../src/Application/Query/BackOffice/Author/Author.php'
            - '../src/Application/Query/BackOffice/Book/Book.php'
            - '../src/Application/Query/Shop/Book/Author.php'
            - '../src/Application/Query/Shop/Book/Book.php'